name: simple_dart_link
description: Simple Link Component
version: 0.0.1
repository: https://github.com/simple-dart/link
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.2
